### ISSUE TITLE
独自メッセージの作成

### ISSUE THREAD

**Issue by ItoMasaki** [rionehome/ros_restaurant#3]
> 経緯

SPRにおいてデータのやり取りの議論を行なっていく上で
データの構造の拡張を行なってきました.
その中で、現在いい感じにまとまっている構造体をメッセージとして用意することで
今後も再利用できるようにできると思います.

> データの内容

- Command : String
- Content : String
- Sender : String

> 利点

このデータ構造をメッセージとして用意する利点として、
ContentやCommand内にデータが保存されているため、
splitやreplace等無駄な処理を行う必要性が減ります.

**Comment by yamatomatsuda** [comment]
@ItoMasaki 
メッセージsenderの内容の詳細

**Comment by ItoMasaki** [comment]
> Senderとは

送信元がどこなのかを保持している.
送る側はSenderに自分のTopicの名前を格納する必要性がある.
受け取り側はそこを参照して判断することで,
動的にフラッグ送信用Publisherを生成できるようになる.

> 経緯

複数のTopicから１つのTopicにデータを送り込むような処理がSPRでは発生して,
その上で処理が終了したことを伝えるためには
明確にどこから送られたものなのかを格納してくことが必要になった.

**Comment by yamatomatsuda** [comment]
@ItoMasaki 
十分に再利用性があると思います。
**rione_msgs**にros2ブランチを作成、
プレビューを作成しましょう
